FROM node:alpine as build

WORKDIR /app
COPY ./package.json /app/
RUN npm install && npm cache clean --force
COPY . /app/

FROM node:alpine

WORKDIR /app
COPY --from=build /app/ .

CMD ["npm", "run", "dev"]