version: '1.0.0'
services:
  client: 
    container_name: app-client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND=http://localhost:4000
    links:
      - backend
  backend:
    container_name: app-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    ports:
      - "4000:4000"