version: '1.0.0'
services:
  client: 
    container_name: app-client
    build: ./client
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NEXT_PUBLIC_BACKEND=http://localhost:4000
    links:
      - backend
  backend:
    container_name: app-backend
    build: ./backend
    ports:
      - "4000:4000"
    privileged: true
##    volumes:
##      - ./backend:/home/code/app
    environment:
      - APP_ENV=docker-development
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /home/code/app
          