import "../styles/index.css";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Terminal App',
    description: 'Generated by create next app',
}

export default function RootLayout(props: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {props.children}
            </body>
        </html>
    )
}
